version: '2.1'

services:
  raveskills:
    image: raveskills-ros2-image
    container_name: raveskills-ros2-container
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - .:/raveskills
      - ../ravestate:/ravestate
      #- /home/roboy/ros2_speech_recognition:/ros2_speech_recognition
    #devices:
    #  - /dev/snd:/dev/snd
    ports:
      - "10002:10002"
      - "9000:9000"
      - "9001:9001"
    environment:
      - PYTHONPATH=$PYTHONPATH:/raveskills/modules:/ravestate/modules:/root/melodic_ws/src/roboy_communication
      - PYTHONUNBUFFERED=1
    # After starting container, attach console and enter python3 -m ravestate [...]
    # This enables "hot reload" in the running container because the source directory is mounted
    command: bash
    tty: true
    stdin_open: true
