version: '2.1'

services:
  ravestate:
    volumes:
      - ../raveskills:/raveskills
    environment:
      - PYTHONPATH=$PYTHONPATH:/raveskills/modules:/ravestate/modules
      - PYTHONUNBUFFERED=1
