# In addition to this file, load a config file `keys.yml`, where
#  `keys.yml` should contain the following content:
#
#   module: telegramio
#   config:
#     telegram-token: <sexycactus>  # Your telegram token here
#   ---
#   module: ontology
#   config:
#     neo4j_address: bolt://localhost:7687  # Your neo4j server uri here
#     neo4j_username: neo4j                 # Your neo4j user here
#     neo4j_pw: <cornycrab>                 # Your neo4j pw here

---
module: core
config:
  tickrate: 10
  import:
    - ravestate_telegramio
    - ravestate_fillers
    - driving
    #- ravestate_wildtalk
    - ravestate_hibye
    #- ravestate_roboyqa
    #- ravestate_genqa
    #- ravestate_persqa
    #- ravestate_sendpics
    #- ravestate_akinator


